import type { Metadata } from "next";
import { Open_Sans as FontSans } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`flex min-h-screen bg-background font-sans antialiased ${fontSans.variable}`}
            >
                <Sidebar />
                <div className="flex flex-grow">
                    <div className="w-[270px]"></div>

                    <div className="flex-grow flex flex-col gap-5 max-w-[calc(100vw-270px)]">
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
