import type { Metadata } from "next";
import { Open_Sans as FontSans } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import "./globals.css";
import ActionTabs from "@/components/ActionTabs";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`flex min-h-screen bg-background font-sans antialiased ${fontSans.variable}`}
            >
                <Sidebar />
                <div className="flex-grow grid grid-cols-[270px_1fr]">
                    <div className=""></div>

                    <div className="flex flex-col gap-5">
                        <Header />

                        <ActionTabs />

                        <div className="px-8">
                            <div className="flex flex-col gap-5 p-5">
                                {children}
                            </div>
                        </div>
                    </div>
                </div>
            </body>
        </html>
    );
}
